version: '3.7'
services:
  postgresql:
    image: postgres:latest
    hostname: postgresql
    container_name: shop-db
    env_file:
      - postgres/.env
    ports:
      - 5434:5432
    volumes:
      - shop-vol:/var/lib/postgresql/data
  web:
    image: alicecoal/shop
    container_name: zz-shop
    user: appuser
    build: ./shop
    env_file:
      - postgres/.env
      - shop/.env
    ports:
      - 8000:8000
    depends_on:
      - postgresql
    command: /bin/bash -c "
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./shop/ishop/:/home/appuser/project
volumes:
  shop-vol:
