version: '3.7'
services:
  postgresql:
    image: postgres:latest
    hostname: postgresql
    container_name: shop-db3
    env_file:
      - postgres/.env
    volumes:
      - shop-vol:/var/lib/postgresql/data
  web:
    image: alicecoal/shop:latest
    container_name: zz-shop3
    user: appuser
    env_file:
      - postgres/.env
      - shop/.env.prod
    ports:
      - 8000:8000
    depends_on:
      - postgresql
    command: /bin/bash -c "
      python3 manage.py runserver 0.0.0.0:8000"
volumes:
  shop-vol:
